CONNECT / AS SYSDBA

alter table scottiv.emp no flashback archive;
alter table scottiv.dept no flashback archive;


DROP FLASHBACK ARCHIVE FDA1;
DROP USER SCOTTIV CASCADE;
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO SCOTTIV IDENTIFIED BY tiger;
GRANT ALTER DATABASE TO SCOTTIV;
GRANT SELECT_CATALOG_ROLE TO SCOTTIV;
GRANT EXECUTE ON DBMS_LOCK TO SCOTTIV;


-- Needed for populating UNDO_SQL
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- Needed for Flashback Transaction Query
GRANT FLASHBACK ANY TABLE TO SCOTTIV;
GRANT SELECT ANY TRANSACTION TO SCOTTIV;

