CONNECT / as sysdba
SET ECHO ON
SET LINESIZE 132

CREATE FLASHBACK ARCHIVE FDA1
TABLESPACE USERS
RETENTION 1 YEAR;

-- Add Tables to FDA1 Archive Area
ALTER TABLE SCOTTIV.EMP FLASHBACK ARCHIVE FDA1;
ALTER TABLE SCOTTIV.DEPT FLASHBACK ARCHIVE FDA1;

-- Archive Area Details
COLUMN FLASHBACK_ARCHIVE_NAME FORMAT A10
SELECT OWNER_NAME,FLASHBACK_ARCHIVE_NAME, RETENTION_IN_DAYS i
  FROM DBA_FLASHBACK_ARCHIVE;

-- Archive Tablespace Details
COLUMN TABLE_NAME FORMAT A10
COLUMN OWNER_NAME FORMAT A10
COLUMN ARCHIVE_TABLE_NAME FORMAT A25
SELECT * FROM DBA_FLASHBACK_ARCHIVE_TS;

-- View Archive table associated with the 
SELECT * FROM DBA_FLASHBACK_ARCHIVE_TABLES;

